### ISSUE TITLE
Quest: Body of Evidence

### ISSUE THREAD

**Issue by scottiedog321** [Helios-Empire/Helios-Tracker#101]
Placing the blanket on the pyre doesn't summon the ogres needed to finish the quest.

http://www.wowhead.com/quest=9932/body-of-evidence
https://www.youtube.com/watch?v=onKEuvTark8

**Comment by dikkedeur** [comment]
confirmed.

**Comment by dikkedeur** [comment]
will be fixed in next core update, when you have the quest you go to the pyre, you dont need to activate it, event will autostart, there is no other way at this moment to make this work.. 
the event will start, 2 ogres will spawn, plant bodies, be sure that the surrounding area is free, so they dont get attacked ^^
when done you get quest credit.
