### ISSUE TITLE
Bug at dead body at any mobs... i can't see all items from drop mob... but with an alt i can see,why?!

### ISSUE THREAD

**Issue by luchiano17** [Helios-Empire/Helios-Tracker#103]

**Comment by dikkedeur** [comment]
you are propably in a group with your alt and one is set as masterlooter??
i havent encounter this problem, maybe you are able to make a better detailed bugreport instead of in the title.

**Comment by Pharzuph** [comment]
with Group Loot you can see money, but not items that are reserved to a player which turn is to loot, easy fixed by setting Free for All. Group loot works-> Each time that mob dies 1 of the party players is granted right to loot that mob, next mob is given to 2nd, next mob to 3rd and so on, till it goes back to 1st player in that circle. Gold is shared so anyone can loot it and non-Junk items(uncommon and above) are Rolled for.
Just mentioned this cos the default setting once you enter the party is Group Loot.

**Comment by dikkedeur** [comment]
not bugged.. moved to closed
