### ISSUE TITLE
Hunter Pet Bugs

### ISSUE THREAD

**Issue by luchiano17** [Helios-Empire/Helios-Tracker#105]
I can't rename my pet
I can't see the happyness of my pet...
I can't see skills my pet from Spellbook

Repair please...

**Comment by dikkedeur** [comment]
i think you have problem with either your client or the pet itself, since i have this.

![schermafbeelding 2015-08-31 om 22 36 45](https://cloud.githubusercontent.com/assets/11842306/9589791/fe2e80cc-5030-11e5-9c83-f31782123be4.png)
![schermafbeelding 2015-08-31 om 22 37 02](https://cloud.githubusercontent.com/assets/11842306/9589802/0ae0115a-5031-11e5-9083-63fa31998e11.png)

![schermafbeelding 2015-08-31 om 22 37 10](https://cloud.githubusercontent.com/assets/11842306/9589808/14d26582-5031-11e5-9c38-825b37bc0f02.png)

**Comment by luchiano17** [comment]
No... 
In this night when i try to play on hunter... my pet have name King Bangalash...  and u can see.... just in this night is for first time when i have this bug... 
![wowscrnshot_083115_234943](https://cloud.githubusercontent.com/assets/14013728/9590063/0cd2cb74-503b-11e5-8cd0-b3ef0a505502.jpg)

**Comment by dikkedeur** [comment]
i did a core update yesterday and that involves as you can see on http://helios-empire.eu/changelog tat pets should react a little bit better, 
although i dont recall that problem before.. and with a new tamed pet i dont have it, so it might be due old pets?? try getting a new pet and see if you still have the problem.. i cant reproduce the bug right now.

**Comment by luchiano17** [comment]
new pet... oh... king bangalash far away.... i will try...
