### ISSUE TITLE
The Second trial Paladin classquest

### ISSUE THREAD

**Issue by Krynaverion** [Helios-Empire/Helios-Tracker#11]
After starting the quests the Enemies spawn as intended and the first one gets attackable, after killing him the second turns red but not attackable. 
After aborting the quest to restart it the quest giver [Master Kelerun Bloodmourn](http://www.wowhead.com/npc=17807) has an exclamation mark but no quest.

Have a nice day

**Comment by HEGladios** [comment]
The script didn't reset properly if someone failed to complete it. This made it so that the questgiver was stuck running the script and didn't allow you to accept or complete quests.
After the next core update (and server crash/restart) the script will reset if there was no progress in the last 3 minutes. So if ever it bugs out, simply wait 3 minutes, abandon and re-accept the quest and try again :)

**Comment by dikkedeur** [comment]
this is still not working gladios, the second person turns now red indeed, but you still get the error you cant attack that target.

after 3 minute, timer passes since nothing happens and then everything despawns and then the questgiver has ! above his head but when you talk nothing, not even when you abandon the quest.
you are not able to take it again.

**Comment by HEGladios** [comment]
Cannot reproduce on dev server. Will need more detailed reproduction steps.

**Comment by dikkedeur** [comment]
well retested it and it does work,
