### ISSUE TITLE
Quest: A spirit guide

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#134]
Whenever i have attempted this quest tonight the server would disconnects me during the wolf's little animation to begin walking. it could have been bad luck but it the D/c only occurred when attempting that quest.

**Comment by dikkedeur** [comment]
it might be, i will test it and i have 2 crashlogs of the same, i think you did it twice :+1:

**Comment by dikkedeur** [comment]
tested it on my dev server and got same result, this quests does crash the core at the moment the spirit wolf sniffes on the dead body.
thank you so much for telling us, we do get crashlogs, but those logs never say where and how it happens, we need feedback from the people from that..
because then its easier to look where it crashes and why.

since crashfixes is not my thing i will forward this one.

**Comment by dikkedeur** [comment]
this is fixed in next core update. i also fixed the speed of the ancient spirit wolf, since it was going way to fast.
