### ISSUE TITLE
The totem of Kar'dash

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#162]
When attempting the quest, the npc that you are suppose to escort out "Mag'har Captive" will attack the player during each wave of spawned attackers. After the mobs are killed the npc will then proceed to attack you until the player runs far enough away for him to reset and continue walking until the next spawn. then rinse and repeat, the annoying part is if you run to far away to drop combat it causes the npc to disappear.

**Comment by dikkedeur** [comment]
note for the devs:
in nagrand.cpp his script says at some line > pCreature->setFaction(232);
that faction is different then the faction on TC, there it is faction 231.
i doubt if the difference in those 2 factions are noticeable, but its worth a try to change the value and see if that works better.
otherwise there must be more checks to do to change his faction state from time to time.

**Comment by HEguinness** [comment]
> pCreature->setFaction(290); should do it.

**Comment by dikkedeur** [comment]
shall try this on the dev server later on tonight if you dont mind :+1:

**Comment by HEguinness** [comment]
Fixed, will be on live after the next restart.

**Comment by dikkedeur** [comment]
will work great for both horde and alliance now after server update.. which will come to a cinema near you.............
