### ISSUE TITLE
Dungeon: Shattered Halls

### ISSUE THREAD

**Issue by Classic-WoW** [Helios-Empire/Helios-Tracker#165]
Hello,

The last couple days we have been grinding the shattered halls for our exalted reputation with the +25% REP buff from thrallmar. So far we have gotten to exalted. After our 20's or so run of killing trash we found out that some mobs in the shattered halls give more reputation then they should (I believe instead of 10 rep they give 50 or so)

If possible please check this, i think you required like at least 30 runs instead of 20.

We also might be wrong, it just seemed pretty fast for us.

**Comment by dikkedeur** [comment]
indeed they give 50, when looking on wowhead they say that they should give 3 rep, but that is based on wod... there are no good documentation found so far that 50 was not the case in tbc and wotlk ( since i looked also on wotlk database and there it is also 50 rep.)

is there a possibility that we can check how it was on tbc times?
if any information can be found im willing to take a look at it.

**Comment by Inyu** [comment]
i found a vid of a run though Shattered Halls but the resolution is rly crappy but 3 rep should be right since the elite mobs give 12 each
heres the link to the vid mb u can see more
https://www.youtube.com/watch?v=ilwK9l18Iqg

**Comment by HEGladios** [comment]
Fixed in next core update, thanks @Absolution2015.
