### ISSUE TITLE
Shadow Council Warlock

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#200]
The mob http://db.helios-empire.eu/?npc=21302 should give Aldor rep when killed, I can't remember how much but I remember being able to farm these for rep in retail and them having roughly a 10 second respawn time. As a side note, they should be casting http://db.helios-empire.eu/?spell=9613 and http://db.helios-empire.eu/?spell=37992 but they aren't do anything but melee.

**Comment by dikkedeur** [comment]
fixed on next core update, the rep. value was nowhere to be found.. since most of the mobs give 3 rep on aldor i have set it to that value.. again it might be too much or to low, i dont know, and there is no documentation of it either on how much on retail it was, since it was removed in patch 5.x that you gain rep from that npc.
they will also cast crap now according to blizzlike standards.

enjoy

**Comment by notaslave** [comment]
Thanks, I wasn't complaining that they didn't cast anything, makes my life easy if they don't lol

**Comment by dikkedeur** [comment]
a bug is a bug, even if it doesnt cast... so thanks for noticing.
