### ISSUE TITLE
Getting Down to Business

### ISSUE THREAD

**Issue by notaslave** [Helios-Empire/Helios-Tracker#203]
While on the quest http://db.helios-empire.eu/?quest=10271 the npc http://db.helios-empire.eu/?npc=20518 will despawn and will not come back when you click on the pad. Thus the quest cannot be turned in.

**Comment by dikkedeur** [comment]
have you look on where and who you need to turn in the quest??
since its not the image of the teleport pad that you are looking for but the shrouded figure ^^
and he is voila

![schermafbeelding 2016-03-09 om 10 09 07](https://cloud.githubusercontent.com/assets/11842306/13630323/1b40a610-e5df-11e5-9cf3-1b0aa8e04fcd.png)

as you can see he is sneaky on the left sitting :+1:

**Comment by notaslave** [comment]
Well, not sure where he was because he wasn't there when I went to turn the quest in lol. thanks though
