### ISSUE TITLE
[Spell] Arcane Torrent doesn't consume stacks

### ISSUE THREAD

**Issue by Cio0** [Helios-Empire/Helios-Tracker#232]
Kind of bug: spell http://db.helios-empire.eu/?spell=28730

What bug do you encounter?:
When no enemy NPC is in range, it won't consume any charges/provide mana. It will occasionally also do this with a mob in range, but cannot determine why/when this happens.

How to reproduce your bug?:
Gather any stacks of 'Mana tap' using http://db.helios-empire.eu/?spell=28734 and then cast Arcane Torrent. See http://imgur.com/a/Uyo8T for screenshots. Combat logs shows nothing, but I've clearly used Arcane Torrent without consuming charges.

How it should work?:
Arcane Torrent should always consume all charges and provide mana.

Operating System:
W7

**Comment by dikkedeur** [comment]
![schermafbeelding 2016-04-14 om 20 20 39](https://cloud.githubusercontent.com/assets/11842306/14538962/840b004e-027e-11e6-9190-36c1d36d74e4.png)

works perfectly by me..
or am i mistaken your bugreport?

when it comes to creature not in range the spell just does nothing, but triggers the cooldown, you still keep your stacks, at least that was in my case, confirming the report.
But should it be just like that, since at first the spell says it only works when silencing a creature.??

**Comment by dikkedeur** [comment]
https://youtu.be/PSiTc3aGL7M
better upload a vid so we know what is going on.

**Comment by Cio0** [comment]
No, it shouldn't be like that. You showed exactly what I did... it doesn't consume stacks properly if no target is affected for the silence portion. This pretty much breaks the mana regen aspect of BE racials.

It should always consume stacks to regen mana when casted, even with no creature in sight. This consuming effect should not be resistible either, and it can't miss. So if a target resist the silence portion, it should still consume stacks and regen mana.

**Comment by dikkedeur** [comment]
understandable, thats what i thought.

**Comment by dikkedeur** [comment]
Fixed
