### ISSUE TITLE
Feral fire (feral) rank 1 is immediately untalented and not refunded upon learning rank 2 from trainer

### ISSUE THREAD

**Issue by ciyle** [Helios-Empire/Helios-Tracker#263]
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
NPC (trainer)
http://db.helios-empire.eu/?spell=16857

What bug do you encounter?:
I was able to learn Faerie Fire (feral) rank 1 from the Feral Combat talent tree. Upon level 30 when I learned rank 2 from a trainer, rank 1 in my talent tree came up as unlearned. I was not refunded a talent point (ie at level 34 I currently have 24 spent points, not 25)

How to reproduce your bug?:
Have a level 30 druid specced into feral combat learn feral fire (feral) rank 1, and then purchase rank 2 from a trainer. The process should unlearn the first rank of the ability.

How it should work?:
Upon learning rank 2 of the ability, rank 2 wouldn't show up as untalented and the talent point should not be consumed

Operating System:
Windows 10
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by dikkedeur** [comment]
dupicate of https://github.com/Helios-Empire/Helios-Tracker/issues/19

Side note: its visual, you are indeed NOT credited, since its still in your spellbook, and you can still learn rank 2 etc.. its only visual, you also CANT put a talent point in it.. since after all its learned, this is a very odd and very old bug, and a lot of cores have this bug and hard to fix, since i have already tried a few so called fixes claiming to fix this bug, but all have failed so far.
