### ISSUE TITLE
[Website] Vote points are not accredited

### ISSUE THREAD

**Issue by Ildsenth** [Helios-Empire/Helios-Tracker#3]
The website is not counting the votes a player casts, and the points are not accredited to the account.

Likely an issue with postbacks (although the issue remains for both votesites that support postback and those that do not).

XtremeTop100 is the only votesite on the list that lacks postback support, so it should be set up accordingly.

**Comment by dikkedeur** [comment]
Hi Ildsenth ,

we are working since yesterday on the votesites, and postback problem, so we are aware of it.
xtremetop100 is also having postback only for gold members, since we are since yesterday.

**Comment by Ildsenth** [comment]
Hello.

I see, didn't know you were gold members there :) Glad it's being sorted out. Also kudos for the fast response :)

**Comment by dikkedeur** [comment]
our server is still in beta stage, and we needed the gold membership to sort out the callbak, wich is what we are still working on.
So our server is not "open" for public, so to see a fast responce from you was like wut?? who is that?
so we are all here on the background, how is that possible, then i explained the gol membership and banner.. and testing.

anyway, the server is open i saw you made an account, dont know if you even have played or made a character yet, but expect we are not official open, so we are still working, we need to make some other progress still until we are satisfied.
but thanks for the input.

greetings
Dikkedeur

**Comment by Ildsenth** [comment]
I found out about the server on TopG, so I thought it was already open for play :) I made a character, but I'm afraid the 1x leveling rates are not my cup of tea.

Just to know, will accounts/characters be deleted once the switch from beta to open?

**Comment by dikkedeur** [comment]
ah, thanks, yeah also on gtop we made account and top100arena, so to check the postback..
Ehh, the accounts and char will stay.. we might increase the xprate, since we know specially in the beginning the leveling will be slow and you need to have some starting point in playerbase.
But it will be i think roughly 3x, and with RAF 6x.
but we still need to work out some things on the server and cms to make it fully how we want.
we will therefor close the account registration page, to avoid more people joining, and being disappointed after that since the server is not ready as we want and advertise.... 

Makeing a server is 1 thing, but finetuning is what takes the most time :+1: 

accounts and chars now made will not be deleted.

**Comment by Ildsenth** [comment]
If I may say my piece of mind, I would personally keep open the registrations and increase the experience rates so that people that find out about the project and think it tickles their interest could still join and tell their friends about it :) Quality comes evident from progress, nothing has to be perfect from the get-go as long as people can "taste" and see with their own eyes the project going forward.

**Comment by HEGladios** [comment]
After a few more changes and fixes to our website we'll move on to the server.
There's only a few key things that we need to change. After that it will quickly be open for players :)

**Comment by Ildsenth** [comment]
I see, nice to hear :) I'm looking forward to it.

**Comment by dikkedeur** [comment]
callback is 100% working for all sites now, and points are given when you vote 100% correctly.
