### ISSUE TITLE
Pet's bug  , no spells

### ISSUE THREAD

**Issue by Anasthasiabg** [Helios-Empire/Helios-Tracker#93]
Hello I'm playing hunter and mine pet doesn't have any attack spells I'm with it from lvl 11 now I'm lvl 20 and the pet  still don't gets any spells like "Bite" I looked at the PET TRAINER but there are no spells .I think   that the pet's are bugged.

**Comment by Inyu** [comment]
Hello pets in TBC have skills when u tame them and u learn those skills if you play with that pet. So in order to get skills you need to tame another pet. Here you can see where to get the skills.
http://web.archive.org/web/20080623060444/http://petopia.brashendeavors.net/html/skills/skills.php
(some of the links are dead since this is from an archive)

**Comment by HEGladios** [comment]
Thanks for your comment Inyu! I'll mark this as closed :)
