### ISSUE TITLE
Warlock Life Tap

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#95]
The skill of warlock's called Life tap, is either broken or the tooltip for the spell is wrong, I'm currently getting around 620 as the exchange rate. The tooltip shows 420, and i currently do not have improved life tap in the talent tree.

**Comment by Pharzuph** [comment]
This spell now benefits from effects which increase your spell damage. At rank 3 and above, the base amount of health lost and mana gained will increase by 80% of your bonus spell damage effects. Talents and items can further modify those values. Rank 1 and 2 receive reduced effect.

-Wow wiki

Next time Life Tap was changed was in 3.3.? patch, so since then as I recall Life Tap scaled with Spirit(not 100% sure) and Spell Power.

**Comment by HEGladios** [comment]
I don't think tooltips reflected damage after modifiers in TBC?
I'll close this issue.
